vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        poster_file:
            uri_prefix: /uploads/images/posters
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        picture_file:
            uri_prefix: /uploads/images/pictures
            upload_destination: '%upload_picture_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
